### ISSUE TITLE
Adapting to other Flamingo models

### ISSUE THREAD

**Issue by dayeggpi** [arjhun/arduino-sf501remote#2]
While I am trying to use your library to make it work with the SF-500S model, I am now blocked at the following step : 

Using the receive example, I finally manage to get some signals from this remote (no other library help me get to this point; so kudos !). In fact, with the receive example, I got a lot of "noise" signals, and when I kept pressing one button of the remote, I would see many times the same signal so I captured it.

For example, the B button , OFF, I get : 

```
remote ID: 0
switch state: on
channel: 15
raw(dec): 4543
raw(bin): 1000110111111
```

Note that I tried many times, and the raw(dec) changes if I try again to capture the B OFF signal later.

Then using the send example, I do : 

```
#include <sf501-remote.h>

Sf501Remote remote;
const int remoteId = 0;

void setup() {

  remote.startTransmitter(13);
}

void loop() {
  
  long command = 4543; 
  remote.sendRaw(command);
}
```

But nothing happens on my switch. The weird thing is that the remote now doesnt work. As if the signal sent by my arduino is "blocking"/flooding the switch.

Am I sending the correct command ?

You are my only lead now, to try to copy a signal from my remote so that I can control my lamps via my arduino.

**Comment by arjhun** [comment]
Hi hycday,

This library is not ment to be used to decode unknown protocols. This library is purely written for the sf501 and for me to learn how to decode radio signals and write an Arduino library. For this to work with other models you need to know the preamble, if there is one, the amount of bits send per buttons press, and you need to know the bit encoding they use to send over the 1s and 0s. Than you need to figure out what those sequences mean. If you could send me packets capturered by a logic analyzer or decoded by Arduino libraries that are able to capture raw data from 433mhz receivers I could reverse engineer it and add it to the library. You need a lot of info to do this. I do not currently own the 500s. Where did you buy it?

Your code currently keeps on sending data on the 433mhz frequency. There is no time for the receiver to listen to other packets. You really need to put a conditional statement in place like the pressing of a button or use the sleep function. The protocols that these cheap remotes use cannot be used bi directionally and in parallel. You have to send them one after the other and resend them a couple of times to make sure the packet is received. (I think there is an example included with the library)

I hope you can figure out a way to decode the packets like I did for the sf501.

Arjen

**Comment by dayeggpi** [comment]
hi arjhun,

thanks for your answer !
no worries at all, i finally managed to decode the sf-500s protocol and use it successfully :)
i managed indeed to get the 2 sync bits as well as the 64 data bit, for each of the buttons (ABC ON OFF)

thanks for your follow up, appreciate it !

hycday

**Comment by arjhun** [comment]
That's awesome! Are you still using this library, did you modify it? Maybe we could add it to this library for future users?

**Comment by dayeggpi** [comment]
I used another library to decode unknown protocol.

I can send you the raw codes of A B C (ON/OFF) if you want, so that you can add it to the library ? (then i can test it easily if you want me to).
The particularity of the signal is that it has 2 sync bits, and I had to use another library to be able to send such signal.
